# field
FIELD_X_RANGE = 30
FIELD_Y_RANGE = 30

# MOVE-TO-TARGET: TARGET POSITION
# TARGET_X_RANGE = 15
# TARGET_Y_RANGE = 12.5
# TARGET_X_LOWER_BOUND = 2.5
# TARGET_Y_LOWER_BOUND = 15

TARGET_X = 20
TARGET_Y = 20

PLAYER_START = 0
SCALER_INIT_ITERATIONS = 1024
STATE_SIZE = 4
VISGRAPH_WORKERS = 1
BATCH_SIZE = 32
BUFFER_SIZE = 512
ROUNDS_PER_BATTLE = 4

# rewards
REW_DIST_MULT = -0.1
REW_FIELD_EDGE = -3
REW_REACHED_TARGET = 20

N_HIDDEN_LAYERS = 2
HIDDEN_DIM = 16

